name: Cloud build test app version to image registry

on:
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - "docker/Dockerfile.client"
      - ".github/workflows/ci-lms-client-docker-image.yaml"

env:
  DOCKER_IMAGE_TAG: "app-version-v.1.0.0"

jobs:
  setup-build-deploy:
    if: github.event.pull_request.merged == true
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: "./docker/Dockerfile.client"
          push: false
          build-args: |
            APP_TAG_VERSION=${{ env.DOCKER_IMAGE_TAG }}
